name: Publish to PyPI/github

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+[ab]?[0-9]?'

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Create github release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/opentaxii*.whl,dist/opentaxii*.tar.gz"
        bodyFile: "CHANGES.rst"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
